#!/usr/bin/env python3
"""
Stalled warm-lead alerter.

A human reply is the scarcest thing this system produces — roughly one in fifty delivered
cold emails earns one. The 2026-09 audit found the pipeline losing them at exactly that
point: `tracker.stalled_conversations()` correctly flagged a founder-level reply that had
been idle for weeks, /status and /followup-check both displayed it, and nothing ever
pushed it to Zineb. A flag nobody reads is not a safety net.

This turns the flag into a push: one email listing every warm thread going cold, with what
the person actually said, so the next action is obvious. Reply-drafting stays manual and
human — this only makes sure the thread is never silently forgotten.

Dedup: a lead is alerted at most once every ALERT_COOLDOWN_DAYS, so a thread that stays
idle nags weekly rather than daily. State lives in cache/stalled_alerts.json.

Usage:
  python stalled_alert.py                 # dry-run: print what would be sent
  python stalled_alert.py --send          # send if there is anything new to report
  python stalled_alert.py --send --min-days 3
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date, datetime
from pathlib import Path

_STATE = Path(__file__).parent / "cache" / "stalled_alerts.json"
ALERT_COOLDOWN_DAYS = 7
ESCALATE_AFTER_DAYS = 15          # idle longer than this is flagged as urgent in the subject


def _load() -> dict:
    try:
        return json.loads(_STATE.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _save(d: dict) -> None:
    _STATE.parent.mkdir(parents=True, exist_ok=True)
    _STATE.write_text(json.dumps(d, indent=2, ensure_ascii=False, sort_keys=True), encoding="utf-8")


def _key(rec: dict) -> str:
    return f"{str(rec.get('Company','')).strip().lower()}|{str(rec.get('Role','')).strip().lower()}"


def due(min_days: int = 5) -> list[dict]:
    """Stalled leads not alerted within the cooldown window, most-stale first."""
    import tracker
    state = _load()
    today = date.today()
    out = []
    for rec in tracker.stalled_conversations(days=min_days):
        last = state.get(_key(rec), {}).get("last_alert")
        if last:
            try:
                if (today - datetime.fromisoformat(last).date()).days < ALERT_COOLDOWN_DAYS:
                    continue
            except Exception:
                pass
        out.append(rec)
    return out


def compose(leads: list[dict]) -> tuple[str, str]:
    worst = max((int(r.get("biz_days_idle") or 0) for r in leads), default=0)
    urgent = worst >= ESCALATE_AFTER_DAYS
    subject = (f"{'[URGENT] ' if urgent else ''}{len(leads)} warm lead"
               f"{'s' if len(leads) != 1 else ''} going cold — {worst} business days idle")

    lines = [
        "These people REPLIED to you. Nothing has moved since.",
        "",
        "A human reply is the rarest thing the agent produces — roughly 1 per 50 delivered",
        "cold emails. Each one below is an opportunity still open, not a lost cause.",
        "",
    ]
    for i, r in enumerate(leads, 1):
        idle = r.get("biz_days_idle", "?")
        lines += [
            f"{i}. {r.get('Company','?')}  —  idle {idle} business days",
            f"   Role:    {str(r.get('Role','') or '')[:90]}",
            f"   Contact: {r.get('Contact Email','')}",
            f"   Status:  {r.get('Status','')}",
            f"   They said: {str(r.get('last_reply','') or '')[:260]}",
            "",
        ]
    lines += [
        "-" * 62,
        "Next step is yours — the agent drafts replies but never sends them.",
        "  /interview-prep COMPANY   prep sheet if this is converting",
        "  /cv-builder COMPANY       role-adapted CV to attach",
        "",
        f"Generated by stalled_alert.py on {date.today().isoformat()}.",
    ]
    return subject, "\n".join(lines)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--send", action="store_true", help="actually send (default: dry-run)")
    ap.add_argument("--min-days", type=int, default=5,
                    help="business days of silence before a lead counts as stalled")
    args = ap.parse_args(argv[1:])

    leads = due(args.min_days)
    if not leads:
        print("[stalled] nothing due — no warm lead is going cold (or all were alerted recently)")
        return 0

    subject, body = compose(leads)
    print(f"[stalled] {len(leads)} lead(s) due\n")
    print(f"SUBJECT: {subject}\n")
    print(body)

    if not args.send:
        print("\n[stalled] dry-run — nothing sent. Re-run with --send.")
        return 0

    import config
    from smtp_send import send_and_log
    to = getattr(config, "INTERNAL_ALERT_EMAIL", None) or getattr(config, "EMAIL_ADDRESS", None)
    if not to:
        print("[stalled] no INTERNAL_ALERT_EMAIL configured — cannot send", file=sys.stderr)
        return 1

    res = send_and_log(to_address=to, subject=subject, body=body, attachment_path=None,
                       new_status=None, kind="alert", dry_run=False)
    if not res.ok:
        print(f"[stalled] send FAILED: {res.error}", file=sys.stderr)
        return 1

    state = _load()
    today = date.today().isoformat()
    for r in leads:
        state[_key(r)] = {"last_alert": today, "idle_at_alert": r.get("biz_days_idle")}
    _save(state)
    print(f"\n[stalled] alert sent to {to}; {len(leads)} lead(s) marked (cooldown "
          f"{ALERT_COOLDOWN_DAYS}d)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
